### ISSUE TITLE
Compilation Issue on GPVMs

### ISSUE THREAD

**Issue by dlast44** [MinervaExpt/MINERvA-101-Cross-Section#1]
Steps prior to this:
1. I pulled main about 10 min. ago.
2. Rebuilt PlotUtils
2. Rebuilt UnfoldUtils
3. Tried to rebuild this code.

Saw the following error:
`/minerva/app/users/dlast/Minerva101_2021_Development/TutorialPackage/src/runEventLoop.cpp: In function ‘bool inferRecoTreeNameAndCheckTreeNames(const string&, const string&, std::__cxx11::string&)’:
/minerva/app/users/dlast/Minerva101_2021_Development/TutorialPackage/src/runEventLoop.cpp:360:84: error: expected primary-expression before ‘>’ token
 ee == nullptr || !truthTree->IsA()->InheritsFrom(TClass::GetClass<TTree>()))
`
in effectively each case where this check occurs. 

No further useful information I see in the build output. I will try and address.

**Comment by dlast44** [comment]
I seem to encounter this issue in the ROOT command line environment as well.

`root [9] testTree->IsA()->InheritsFrom(TClass::GetClass<TTree>())
ROOT_prompt_9:1:48: error: 'TTree' does not refer to a value
testTree->IsA()->InheritsFrom(TClass::GetClass<TTree>())
                                               ^
/cvmfs/minerva.opensciencegrid.org/minerva/hep_hpc_products/root/v6_10_04d/Linux64bit+3.10-2.17-e14-prof/etc/../include/RooVectorDataStore.h:34:7: note: declared here
class TTree ;
      ^
ROOT_prompt_9:1:55: error: expected expression
testTree->IsA()->InheritsFrom(TClass::GetClass<TTree>())
`

**Comment by dlast44** [comment]
It appears to be well defined in the ROOT interactive environment, and return true for an actual TTree if I make the following replacement:
`TClass::GetClass<TTree>()` becomes `TClass::GetClass("TTree")`

Going to test the compilation on GPVM.

**Comment by dlast44** [comment]
GPVM compilation worked with the above change. Needs testing on other platforms before I'd like to push to main/close the issue.

**Comment by aolivier23** [comment]
Yeah, that is an easy change.  Just go ahead and commit it on main.  Thanks David.

**Comment by dlast44** [comment]
Committed and pushed. Closing this issue.
